# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.8.5
maven_group=org.btwr.shared_library
archives_base_name=btwr-shared-library

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.116.15+1.21.1

cloth_config_version=15.0.140
mod_menu_version=11.0.3
emi_version=1.1.12+1.21
tough_environment_version=0.13.4
leave_my_bars_alone_version=v21.1.2-1.21.1-Fabric
puzzles_lib_version=v21.1.39-1.21.1-Fabric
forge_config_api_port_version=v21.1.6-1.21.1-Fabric
night_config_version=3.8.3
tough_as_nails_version=10.1.0.13
glitch_core_version=2.1.0.0
hearty_meals_version=1.21-r5
cardinal_components_api_version=6.1.2
midnightlib_version=1.7.5+1.21.1-fabric

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G